In [ ]:
1. 다음 보기와 같이 0이상 10미만의 3x3 모양의 정수 난수를 생성하고 각 행의 첫 번째 값으로 정렬하세요. (5점)

In [13]:
import numpy as np
import pandas as pd
rng = np.random.default_rng(0)
a = rng.integers(0,10,size=((3,3)),dtype='int32')
print(np.sort(a,axis=1))

[[5 6 8]
 [0 2 3]
 [0 0 1]]


In [ ]:
2. 8x8 모양의 정수 0으로 채워진 행렬을 만들고 다음과 인덱싱과 슬라이싱을 이용하여 다음과 같은 체크보드 패턴을
만드세요. (5점)
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [ ]:
zero = np.zeros((8,8),dtype='int32')
zero[[1,3,5,7],0:1]=1
zero[[0,2,4,6],1:2]=1
zero[[1,3,5,7],2:3]=1
zero[[0,2,4,6],3:4]=1
zero[[1,3,5,7],4:5]=1
zero[[0,2,4,6],5:6]=1
zero[[1,3,5,7],6:7]=1
zero[[0,2,4,6],7:8]=1
print(zero)

3. [0,1) 사이의 값을 갖는 크기 10의 랜덤 벡터를 만들고 최대값을 0으로 바꾸는 코드를 만드세요. (5점)

In [12]:
a[np.random.rand()<=0]
print(a)

[0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293 ]


4.경계가 1이고 내부가 0인 5X5 모양의 2차원 배열을 만드세요. (5점)
[[1 1 1 1 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 1 1 1 1]]

In [7]:
import numpy as np
one = np.ones((5,5))
one[1:4,1:4] = 0
print(one)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


5. 0이상 10미만의 난수 정수를 3x3모양으로 생성 후 2번째 열 값을 기준으로 정렬하세요. (seed값 0으로 고정) (5점)

In [24]:
np.random.seed(0)
d = np.random.randint(0,10,(3,3))
sort = np.argsort(d)[:,[2]]
print(d[sort])

[[5 0 3]
 [3 7 9]
 [3 5 2]]
[[[5 0 3]]

 [[3 5 2]]

 [[3 7 9]]]


6.  월드컵 출전선수 골 기록 데이터 분석 (30점)
③ Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케
이스가 존재한다. 해당 건은 몇 건인지 출력하시오. (hint: for문 이용)
④ 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고
전체 데이터 행의 숫자를 출력하시오. (hint: 년도 표기가 4자리 숫자가 아닌 경우를 검사하는 함수를 만든 후 apply
함수를 이용하여 year 컬럼에 적용)
⑤ 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.
⑥ yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
⑦ 2002년도에 출전한 전체 선수 수를 구하시오.
⑧ 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.


In [35]:
#① 주어진 전체 기간의 각 나라별 골 득점수 합계 상위 5개 국가와 그 득점수를 출력하시오

import pandas as pd
df = pd.read_csv("worldcupgoals.csv")
df.groupby('Country')['Goals'].sum().sort_values(ascending=False).head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1295 entries, 0 to 1294
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Player   1295 non-null   object
 1   Goals    1295 non-null   int64 
 2   Years    1295 non-null   object
 3   Country  1295 non-null   object
dtypes: int64(1), object(3)
memory usage: 40.6+ KB
None


Country
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115
Name: Goals, dtype: int64

In [60]:
# ② 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.
dd = df.groupby('Country')['Player'].count().sort_values(ascending=False).head(5)
print(dd)

Country
Brazil       81
Germany      78
Italy        60
Argentina    59
France       58
Name: Player, dtype: int64


# 7. 전 세계 행복도 지수 데이터 분석 (25점)
# ⑦ 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

In [146]:
# ① 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.

import pandas as pd
df = pd.read_csv("happiness.csv")
df1 = df.loc[df["행복랭킹"]<=10]
df1 = df1.groupby('년도')['점수'].mean().sort_values(ascending=False)
print(df1)

년도
2019    7.4559
2018    7.4442
Name: 점수, dtype: float64


In [147]:
# ② 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.

df2 = df.loc[df["행복랭킹"]<=50]
df2 = df2.groupby(['년도','나라명'])[['점수']].mean()
dfs = pd.DataFrame(df2, index=df2.index, columns=["점수"])
display(dfs)

점수
년도   나라명                        
2018 Argentina             6.388
     Australia             7.272
     Austria               7.139
     Bahrain               6.105
     Belgium               6.927
...                          ...
2019 United Arab Emirates  6.825
     United Kingdom        7.054
     United States         6.892
     Uruguay               6.293
     Uzbekistan            6.174

[100 rows x 1 columns]

In [162]:
# ③ 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.

df0 = df.loc[df["년도"]==2018]
df0 = df0.groupby(['년도','나라명'])[['점수']].mean().sort_values('점수',ascending=True).head(5)
df1 = df.loc[df["년도"]==2019]
df1 = df1.groupby(['년도','나라명'])[['점수']].mean().sort_values('점수',ascending=True).head(5)

print(df0,df1)

                                  점수
년도   나라명                            
2018 Burundi                   2.905
     Central African Republic  3.083
     South Sudan               3.254
     Tanzania                  3.303
     Yemen                     3.355                                   점수
년도   나라명                            
2019 South Sudan               2.853
     Central African Republic  3.083
     Afghanistan               3.203
     Tanzania                  3.231
     Rwanda                    3.334


In [213]:
# ④ 2019년 데이터를 추출하고 해당 데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을
# 각각 구하고 그 차이 값을 출력하시오

df5 = df.loc[df["년도"]==2019]
df1 = df5.drop(['나라명'],axis=1).mean()
GDP_HIGH = df5["상대GDP"]>= GDP
GDP_low = df5["상대GDP"]<= GDP

df6 = df5.loc[GDP_HIGH]
HighMean = df6['점수'].mean()

df6 = df5.loc[GDP_low]
lowMean = df6['점수'].mean()

print(HighMean-lowMean)

1.390483957219251


In [236]:
# ⑤ 각 년도의 부패에 대한 인식을 내림차순 정렬했을 때 상위 20개 국가의 부패에 대한 인식의 평균을 구하시오.
df0 = df.loc[df["년도"]==2018]
df1 = df0.sort_values('부패에 대한인식',ascending=True)

df2 = df.loc[df["년도"]==2019]
df3 = df2.sort_values('부패에 대한인식',ascending=True)

print(df1["부패에 대한인식"].head(20).mean(),df3["부패에 대한인식"].head(20).mean())

0.018600000000000005 0.018250000000000006
