1. 다음 보기와 같이 0이상 10미만의 3x3 모양의 정수 난수를 생성하고 각 행의 첫 번째 값으로 정렬하세요. (5점)

In [2]:
import numpy as np
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,0].argsort()])

[[7 0 6]
 [0 2 6]
 [4 0 0]]
[[0 2 6]
 [4 0 0]
 [7 0 6]]


2. 8x8 모양의 정수 0으로 채워진 행렬을 만들고 다음과 인덱싱과 슬라이싱을 이용하여 다음과 같은 체크보드 패턴을
만드세요. (5점)
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [5]:
a = np.zeros((8,8),dtype=int)
print(a)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. [0,1) 사이의 값을 갖는 크기 10의 랜덤 벡터를 만들고 최대값을 0으로 바꾸는 코드를 만드세요. (5점)

In [9]:
a = np.random.rand(10)
a[a.max() == a] = 0 // a[a.argmax()]=0
print(a)

[0.01594769 0.64692618 0.69298683 0.69064355 0.03943618 0.67358312
 0.67885024 0.51115096 0.         0.61397116]


4.경계가 1이고 내부가 0인 5X5 모양의 2차원 배열을 만드세요. (5점)
[[1 1 1 1 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 1 1 1 1]]

In [11]:
a = np.ones((5,5),dtype=int)
a[1:-1,1:-1] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


5. 0이상 10미만의 난수 정수를 3x3모양으로 생성 후 2번째 열 값을 기준으로 정렬하세요. (seed값 0으로 고정) (5점)

In [12]:
np.random.seed(0)
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[5 0 3]
 [3 7 9]
 [3 5 2]]
[[5 0 3]
 [3 5 2]
 [3 7 9]]


6. 월드컵 출전선수 골 기록 데이터 분석 (30점)

① 주어진 전체 기간의 각 나라별 골 득점수 합계 상위 5개 국가와 그 득점수를 출력하시오

In [14]:
import pandas as pd
df = pd.read_csv('worldcupgoals.csv')
print(df.head())

           Player  Goals                Years  Country
0  Miroslav Klose     16  2002-2006-2010-2014  Germany
1         Ronaldo     15       1998-2002-2006   Brazil
2     Gerd Muller     14            1970-1974  Germany
3   Just Fontaine     13                 1958   France
4            Pele     12  1958-1962-1966-1970   Brazil


In [17]:
result = df.groupby('Country')['Goals'].sum('Goals').sort_values(ascending=False).head(5)
print(result)

Country
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115
Name: Goals, dtype: int64


② 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.

In [16]:
result = df.groupby('Country')['Player'].agg('count').sort_values(ascending=False).head(5)
print(result)

Country
Brazil       81
Germany      78
Italy        60
Argentina    59
France       58
Name: Player, dtype: int64


③ Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케이스가 존재한다. 해당 건은 몇 건인지 출력하시오. (hint: for문 이용)

In [19]:
count = 0
for years in df['Years']:
    for year in years.split('-'):
        if len(year) != 4:
            #print(year)
            count+=1
print(count)        

45


④ 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고 전체 데이터 행의 숫자를 출력하시오. (hint: 년도 표기가 4자리 숫자가 아닌 경우를 검사하는 함수를 만든 후 apply 함수를 이용하여 year 컬럼에 적용

In [22]:
def checkYearFormat(years):
        for year in years.split('-'):
            if len(year) != 4:
                return False
        return True
print(count) 
df['year_check']=df['Years'].apply(checkYearFormat)

45


In [24]:
print(df.shape[0])

1295


In [25]:
df_new = df[df['year_check']]
print(df_new.shape[0])

1250


⑤ 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.

In [26]:
df_new['LenCup'] = [len(years.split('-')) for years in df_new['Years']]
print(df_new['LenCup'].sample(10))

5       3
498     1
52      2
1018    2
187     2
18      3
320     2
516     1
367     2
577     1
Name: LenCup, dtype: int64


C:\Users\user\AppData\Local\Temp\ipykernel_23772\647621108.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['LenCup'] = [len(years.split('-')) for years in df_new['Years']]


In [27]:
result = df_new[df_new['LenCup']==4]
print(result.size)

96


⑥ yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.

In [30]:
result = df_new[df_new['Country'] == 'Yugoslavia'][df_new['LenCup']==2]
print(len(result))

7


C:\Users\user\AppData\Local\Temp\ipykernel_23772\915229326.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = df_new[df_new['Country'] == 'Yugoslavia'][df_new['LenCup']==2]


⑦ 2002년도에 출전한 전체 선수 수를 구하시오.

In [31]:
result = df_new[df_new['Years'].str.contains('2002')]
print(len(result))

156


⑧ 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [32]:
result = df_new[df_new['LenCup'] == 1].sort_values('Goals',ascending=False).head(1)[['Player','Goals']]
print(result)

          Player  Goals
3  Just Fontaine     13


7. 전 세계 행복도 지수 데이터 분석 (25점)

In [33]:
import pandas as pd
df = pd.read_csv('happiness.csv')

In [ ]:
① 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.

In [34]:
grouped = df.groupby('년도')
for year, group in grouped:
    print('년도:', year)
    print(group[group['행복랭킹'] <= 10]['점수'].mean().round(2))

년도: 2018
7.44
년도: 2019
7.46


In [37]:
result = df[df['행복랭킹']<= 10].groupby('년도')['점수'].mean().round(2)
print(result)

년도
2018    7.44
2019    7.46
Name: 점수, dtype: float64


② 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.

In [38]:
result = df[df['행복랭킹']<= 50].groupby('년도')['점수'].mean().round(2)
print(result)

년도
2018    6.65
2019    6.67
Name: 점수, dtype: float64


③ 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.

In [41]:
result = df.sort_values(['년도','점수']).groupby('년도').head(5).groupby('년도')['점수'].mean().round(2)
display(result)

년도
2018    3.18
2019    3.14
Name: 점수, dtype: float64

④ 2019년 데이터를 추출하고 해당 데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을 각각 구하고 그 차이 값을 출력하시오

In [42]:
df_2019 = df[df['년도'] == 2019]
over_mean = df_2019[df_2019['상대GDP'] >= df_2019['상대GDP'].mean()]['점수'].mean()
under_mean = df_2019[df_2019['상대GDP'] <= df_2019['상대GDP'].mean()]['점수'].mean()
print(np.round(over_mean - under_mean,2))

1.39


⑤ 각 년도의 부패에 대한인식을 내림차순 정렬했을 때 상위 20개 국가의 부패에 대한인식의 평균을 구하시오.

In [50]:
result = df.sort_values(['년도','부패에 대한인식'],ascending=False).groupby('년도').head(20).groupby('년도')['부패에 대한인식'].mean().round(4)
print(result)

년도
2018    0.3267
2019    0.3201
Name: 부패에 대한인식, dtype: float64


⑥ 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하시오.

In [51]:
df1 = df[np.logical_and(df['년도']==2019,df['행복랭킹']<=50)]['나라명']
df2 = df[np.logical_and(df['년도']==2019,df['행복랭킹']>50)]['나라명']
result = df2.isin(df1).sum()
print(result)

0


⑦ 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

In [57]:
year_2018 = df[df['년도']==2018]['나라명']
year_2019 = df[df['년도']==2019]['나라명']
year_2018_2019_masking = year_2019.isin(year_2018)
year_2018_2019 = year_2019[year_2018_2019_masking]
print(year_2018_2019)

0                       Finland
1                       Denmark
2                        Norway
3                       Iceland
4                   Netherlands
                 ...           
151                      Rwanda
152                    Tanzania
153                 Afghanistan
154    Central African Republic
155                 South Sudan
Name: 나라명, Length: 152, dtype: object


In [58]:
count = df['나라명'].value_counts()
year_2018_2019 = count[count == 2].index
print(year_2018_2019)

Index(['Finland', 'Albania', 'Nepal', 'Jordan', 'Benin', 'Congo (Brazzaville)',
       'Gabon', 'Laos', 'South Africa', 'Venezuela',
       ...
       'Kosovo', 'Romania', 'Cyprus', 'Argentina', 'Kuwait', 'Thailand',
       'Latvia', 'South Korea', 'Estonia', 'Jamaica'],
      dtype='object', name='나라명', length=152)


In [59]:
multiple =df[df['나라명'].isin(year_2018_2019)]

year_2019 = multiple[multiple['년도']==2019].sort_values('나라명')
year_2018_point = multiple[multiple['년도']==2018].sort_values('나라명')['점수']
year_2019['전년대비 점수 증감'] = year_2019['점수'].values - year_2018_point.values

year_2019[year_2019['전년대비 점수 증감'].max() == year_2019['전년대비 점수 증감']] [['나라명','전년대비 점수 증감']]

나라명  전년대비 점수 증감
144  Burundi        0.87

In [ ]:
8. 유튜브 데이터 분석 (20점)

In [ ]:
① 컬럼의 이름을 다음과 같이 변경하시오
◼title : 채널명, category : 카테고리, subscriber : 구독자수, view : 조회수, video : 영상개수

In [61]:
import pandas as pd
df = pd.read_csv('youtube_rank.csv')

In [62]:
df.columns = ['채널명','카테고리','구독자수','조회수','영상개수']

② ‘구독자수’ 컬럼과 ‘조회수’ 컬럼의 타입을 정수형(int64)로 변경하시오 (‘억’,’만’ 한글을 삭제 후 숫자로 변경)

In [91]:
df['구독자수'] = df['구독자수'].replace('만','0000',regex=True).astype('int64')
df['조회수'] = df['조회수'].replace(['만','억'],['','0000'],regex=True).astype('int64')       

In [ ]:
③ ‘영상개수’ 컬럼의 ‘,’와 ‘개’문자를 제거하고 정수형(int32)로 변경하시오.

In [84]:
df['영상개수'] = df['영상개수'].replace([',','개'],['',''],regex=True).astype('int32')       

In [ ]:
④ 인기 채널 확인하기
◼’구독자수’와 ‘조회수’가 많은 5개의 채널을 각각 출력하시오

In [69]:
df.sort_values('구독자수',ascending=False).head(5)
df.sort_values('조회수',ascending=False).head(5)

채널명        카테고리   구독자수          조회수   영상개수
4            SMTOWN  [음악/댄스/가수]  2450만  18000007532   3583
6      1theK (원더케이)  [음악/댄스/가수]  2090만  17800006042  13291
8  ArianaGrandeVevo  [음악/댄스/가수]  1820만  14700009692    112
0         BLACKPINK  [음악/댄스/가수]  5140만  12800005130    319
1    Big Hit Labels  [음악/댄스/가수]  4550만  12000008966    433

In [ ]:
⑤ ‘카테고리’가 [음악/댄스/가수]인 채널의 ‘구독자수’ 상위 5개를 출력하시오.

In [78]:
result = df[df['카테고리'] == '[음악/댄스/가수]'].sort_values(by='카테고리', ascending=False).head(5)
print(result)

                       채널명        카테고리   구독자수          조회수  영상개수
0                BLACKPINK  [음악/댄스/가수]  5140만  12800005130   319
577                 DKDKTV  [음악/댄스/가수]    67만    100002446   909
531  Dreamcatcher official  [음악/댄스/가수]    73만    100000329   239
539    ALL THE K-JAM 올더케이잼  [음악/댄스/가수]    72만    500009963  9564
548            wondergirls  [음악/댄스/가수]    71만    300003872   217


In [79]:
result = df[df['카테고리'].isin(['TV/방송]','[게임]'])]
print(len(result))

101


In [ ]:
⑦ ‘채널명’에 ‘KBS’가 포함된 채널 명을 출력하시오.

In [86]:
print(df[df['채널명'].str.contains('KBS')])

                          채널명        카테고리   구독자수          조회수    영상개수
12                  KBS World     [TV/방송]  1430만  10100005806   46830
46                   KBS Kpop     [TV/방송]   526만   3400001126   24389
76              KBS Entertain     [TV/방송]   393만   5300004091   91783
101                 KBS Drama     [TV/방송]   304만   3500003851  105922
290                  KBS 한국방송     [TV/방송]   122만   1100002851   25993
292         KBS Drama Classic  [뉴스/정치/사회]   121만   1000008440    8783
308           KBS HUMAN: 뭉클티비     [TV/방송]   117만    400009568    1593
389                  KBS News  [뉴스/정치/사회]    96만   1000001741  145515
457                KBS CoolFM     [TV/방송]    84만    400002952    6981
716                     KBS N     [TV/방송]    56만    700004783   12470
777                  KBS KONG  [뉴스/정치/사회]    52만    100009161    6639
991  KBS Documentary [KBS 다큐]  [뉴스/정치/사회]    40만    200004506   48383
992                    KBS 교양  [뉴스/정치/사회]    40만    200009796   64694


In [ ]:
⑧ ‘카테고리’별 ‘구독자수’, ‘조회수’, ‘영상개수’의 평균을 출력하시오

In [92]:
result = df.groupby('카테고리')[['구독자수','조회수','영상개수']].mean().round(2)
print(result)

                   구독자수           조회수      영상개수
카테고리                                           
[BJ/인물/연예인]  1274411.76  3.617695e+08    837.74
[IT/기술/컴퓨터]   806250.00  1.125064e+08   1200.12
[TV/방송]      1219875.78  6.677069e+08   9025.13
[게임]          743564.36  4.049554e+08   2527.01
[교육/강의]       851304.35  1.347869e+08    837.91
[국내/해외/여행]    626000.00  1.200067e+08    830.20
[뉴스/정치/사회]   1226964.29  1.141077e+09  42048.09
[미분류]        1429500.00  3.600049e+08    778.05
[스포츠/운동]      932500.00  2.166729e+08   3954.92
[애완/반려동물]    1161000.00  3.850036e+08    786.25
[영화/만화/애니]    852727.27  2.697019e+08    770.18
[음식/요리/레시피]  1612045.45  3.556870e+08    830.02
[음악/댄스/가수]   3195200.00  1.041148e+09   1382.05
[자동차]         490000.00  1.500036e+08    670.00
[주식/경제/부동산]   626000.00  2.000480e+07   1026.40
[취미/라이프]      974500.00  1.625042e+08    359.32
[취미]          560000.00  1.000006e+08    237.00
[키즈/어린이]     2729157.89  1.227374e+09   1069.16
[패션/미용]       823859.65  5.614517e+07   